okta:
  oauth2:
    issuer: https://{yourOktaDomain}/oauth2/default
    client-secret: {clientId}
    client-id: {clientSecret}
    scopes: openid, profile, email

service:
  github: https://api.github.com

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: {githubClientId}
            client-secret: {githubClientSecret}
